# German common name -> scientific name, ported from wuerttemberg_1/species_gam.R
DE_TO_SCI = {
    "Amsel": "Turdus merula", "Bachstelze": "Motacilla alba", "Baumfalke": "Falco subbuteo",
    "Baumpieper": "Anthus trivialis", "Blaumeise": "Cyanistes caeruleus", "Blässhuhn": "Fulica atra",
    "Braunkehlchen": "Saxicola rubetra", "Buchfink": "Fringilla coelebs", "Buntspecht": "Dendrocopos major",
    "Eichelhäher": "Garrulus glandarius", "Eisvogel": "Alcedo atthis", "Elster": "Pica pica",
    "Feldlerche": "Alauda arvensis", "Feldschwirl": "Locustella naevia", "Feldsperling": "Passer montanus",
    "Fichtenkreuzschnabel": "Loxia curvirostra", "Fitis": "Phylloscopus trochilus",
    "Gartenbaumläufer": "Certhia brachydactyla", "Gartengrasmücke": "Sylvia borin",
    "Gartenrotschwanz": "Phoenicurus phoenicurus", "Gebirgsstelze": "Motacilla cinerea",
    "Gelbspötter": "Hippolais icterina", "Gimpel": "Pyrrhula pyrrhula", "Girlitz": "Serinus serinus",
    "Goldammer": "Emberiza citrinella", "Grauschnäpper": "Muscicapa striata", "Grauspecht": "Picus canus",
    "Grünspecht": "Picus viridis", "Haubenmeise": "Lophophanes cristatus",
    "Hausrotschwanz": "Phoenicurus ochruros", "Haussperling": "Passer domesticus",
    "Heckenbraunelle": "Prunella modularis", "Heidelerche": "Lullula arborea",
    "Hohltaube": "Columba oenas", "Höckerschwan": "Cygnus olor",
    "Kernbeißer": "Coccothraustes coccothraustes", "Kleiber": "Sitta europaea",
    "Kohlmeise": "Parus major", "Kolkrabe": "Corvus corax", "Kuckuck": "Cuculus canorus",
    "Mauersegler": "Apus apus", "Mehlschwalbe": "Delichon urbicum", "Misteldrossel": "Turdus viscivorus",
    "Mäusebussard": "Buteo buteo", "Mönchsgrasmücke": "Sylvia atricapilla",
    "Nachtigall": "Luscinia megarhynchos", "Neuntöter": "Lanius collurio", "Pirol": "Oriolus oriolus",
    "Rabenkrähe": "Corvus corone", "Rauchschwalbe": "Hirundo rustica", "Rebhuhn": "Perdix perdix",
    "Ringeltaube": "Columba palumbus", "Rohrammer": "Emberiza schoeniclus",
    "Rotkehlchen": "Erithacus rubecula", "Rotmilan": "Milvus milvus", "Schafstelze": "Motacilla flava",
    "Schwanzmeise": "Aegithalos caudatus", "Schwarzkehlchen": "Saxicola rubicola",
    "Schwarzmilan": "Milvus migrans", "Schwarzspecht": "Dryocopus martius",
    "Singdrossel": "Turdus philomelos", "Sommergoldhähnchen": "Regulus ignicapilla",
    "Sperber": "Accipiter nisus", "Star": "Sturnus vulgaris", "Steinschmätzer": "Oenanthe oenanthe",
    "Stieglitz": "Carduelis carduelis", "Stockente": "Anas platyrhynchos",
    "Sumpfmeise": "Poecile palustris", "Sumpfrohrsänger": "Acrocephalus palustris",
    "Tannenmeise": "Periparus ater", "Teichhuhn": "Gallinula chloropus",
    "Teichrohrsänger": "Acrocephalus scirpaceus", "Trauerschnäpper": "Ficedula hypoleuca",
    "Turmfalke": "Falco tinnunculus", "Turteltaube": "Streptopelia turtur",
    "Türkentaube": "Streptopelia decaocto", "Wacholderdrossel": "Turdus pilaris",
    "Wachtel": "Coturnix coturnix", "Waldbaumläufer": "Certhia familiaris",
    "Waldkauz": "Strix aluco", "Waldlaubsänger": "Phylloscopus sibilatrix",
    "Wanderfalke": "Falco peregrinus", "Weidenmeise": "Poecile montanus",
    "Wendehals": "Jynx torquilla", "Wiesenpieper": "Anthus pratensis",
    "Wintergoldhähnchen": "Regulus regulus", "Zaunkönig": "Troglodytes troglodytes",
    "Zilpzalp": "Phylloscopus collybita",
}
